### PR TITLE
Visuino

### PR DESCRIPTION
**Pull request by tcpipchip**
Please, can you add this DOC?
I dont know where to put in left size the MENU to it.

### CODE REVIEW

**Review by carbonfix — APPROVED** [review]

**Comment by tcpipchip** [comment]
thank you @carbonfix

**Comment by carbonfix** [comment]
You're welcome. I've added it to our resources sidebar and linked it on the Arduino page. Thanks for your work!

**Comment by tcpipchip** [comment]
hi @carbonfix 
mine and Mitov work too!

**Comment by tcpipchip** [comment]
I need to add this too soon
https://milk-v.blogspot.com/2025/02/milk-v-criando-dataset-to-zero-buggio.html

**Pull request merged**
